# Enconding categorical features

In [1]:
import pandas as pd

## Load the data

In [5]:
titanic = pd.read_csv('http://bit.ly/kaggletrain',index_col = 'PassengerId')
titanic.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

## Select features

In [7]:
titanic.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [10]:
titanic.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [12]:
titanic = titanic.loc[titanic.Embarked.notna(),['Survived',
                                         'Pclass',
                                          'Sex',
                                          'Embarked']]

In [19]:
titanic.isnull().sum()

Survived    0
Pclass      0
Sex         0
Embarked    0
dtype: int64

## Cross-validate a model with one feature

In [15]:
X = titanic.loc[:,'Pclass']
y = titanic.Survived

In [34]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='lbfgs')

In [35]:
from sklearn.model_selection import cross_val_score
cross_val_score(logreg,X,y,cv=5,scoring='accuracy').mean()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Expected 2D array, got 1D array instead:
array=[1. 3. 1. 3. 3. 1. 3. 3. 1. 2. 3. 3. 2. 3. 1. 3. 3. 2. 3. 3. 2. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 1. 3. 2. 3. 2. 3. 1. 3. 2. 1. 2. 3. 2. 3. 3. 1. 3. 2.
 3. 2. 3. 1. 3. 2. 3. 2. 3. 2. 2. 2. 2. 3. 3. 2. 3. 3. 1. 3. 2. 1. 2. 3.
 3. 1. 3. 3. 3. 1. 1. 1. 2. 3. 3. 1. 1. 3. 2. 3. 3. 1. 1. 1. 3. 2. 1. 3.
 1. 3. 2. 3. 3. 3. 3. 3. 3. 1. 3. 3. 3. 2. 3. 1. 1. 2. 3. 3. 1. 3. 1. 1.
 1. 3. 3. 3. 2. 3. 1. 1. 1. 2. 1. 1. 1. 2. 3. 2. 3. 2. 2. 1. 1. 3. 3. 2.
 2. 3. 1. 3. 2. 3. 1. 3. 1. 1. 3. 1. 3. 1. 1. 3. 1. 2. 1. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 1. 3. 3. 3. 3. 1. 2. 3. 3. 3. 2. 3. 3. 3. 3. 1. 3. 3. 1. 1.
 3. 3. 1. 3. 1. 3. 1. 3. 3. 1. 3. 3. 1. 3. 2. 3. 2. 3. 2. 1. 3. 3. 1. 3.
 3. 3. 2. 2. 2. 3. 3. 3. 3. 3. 2. 3. 2. 3. 3. 3. 3. 1. 2. 3. 3. 2. 

nan

## Encode categorical features

In [36]:
titanic.head()

Survived  Pclass     Sex Embarked
PassengerId                                   
1                   0       3    male        S
2                   1       1  female        C
3                   1       3  female        S
4                   1       1  female        S
5                   0       3    male        S

In [42]:
# dummy encoding of categorical features
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

In [43]:
ohe.fit_transform(titanic[['Sex']])

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [44]:
ohe.categories_

[array(['female', 'male'], dtype=object)]

In [46]:
ohe.fit_transform(titanic[['Embarked']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [48]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [51]:
ohe.fit_transform(titanic[['Sex','Embarked']])

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [52]:
ohe.categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

## Cross-validate a Pipeline with all features

In [53]:
X = titanic.drop('Survived', axis='columns')
X.head()

Pclass     Sex Embarked
PassengerId                         
1                 3    male        S
2                 1  female        C
3                 3  female        S
4                 1  female        S
5                 3    male        S

In [54]:
# use when different features need different preprocessing
from sklearn.compose import make_column_transformer

In [55]:
column_trans = make_column_transformer(
    (OneHotEncoder(), ['Sex', 'Embarked']),
    remainder='passthrough')

In [56]:
column_trans.fit_transform(X)

array([[0., 1., 0., 0., 1., 3.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 3.],
       ...,
       [1., 0., 0., 0., 1., 3.],
       [0., 1., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 3.]])

In [58]:
# chain sequential steps together
from sklearn.pipeline import make_pipeline

In [59]:
pipe = make_pipeline(column_trans, logreg)

In [60]:
# cross-validate the entire process
# thus, preprocessing occurs within each fold of cross-validation
cross_val_score(pipe, X, y, cv=5, scoring='accuracy').mean()

0.7727924839713071

## Make predictions on new data

In [61]:
X_new = X.sample(5, random_state=99)
X_new

Pclass     Sex Embarked
PassengerId                         
600               1    male        C
513               1    male        S
274               1    male        C
216               1  female        C
791               3    male        Q

In [62]:
pipe.fit(X, y)

Pipeline(memory=None,
         steps=[('columntransformer',
                 ColumnTransformer(n_jobs=None, remainder='passthrough',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories='auto',
                                                                drop=None,
                                                                dtype=<class 'numpy.float64'>,
                                                                handle_unknown='error',
                                                                sparse=True),
                                                  ['Sex', 'Embarked'])],
                                   verbose=False)),
                ('logisticregression',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                         

In [63]:
pipe.predict(X_new)

array([1, 0, 1, 1, 0], dtype=int64)